### ISSUE TITLE
Website oficial devia ser um link? 

### ISSUE THREAD

**Issue by p1nh0** [Digitopia/digitopia.github.io#2]
Do lado esquerdo, por cima do logo da digitópia, o website oficial deveria ser um link ???
@augusto666  @jasgomes

**Comment by augusto666** [comment]
@p1nh0 o que sugerias, apenas uma imagem?

**Comment by p1nh0** [comment]
fd539bbaf6161bc9e1b5f73aebcd156beecaf143

vê como está agora
