### ISSUE TITLE
Remove .html from links

### ISSUE THREAD

**Issue by nunoh** [Digitopia/digitopia.github.io#4]
Our links are currently showing up in the browser like so `http://digitopia.github.io/research.html`, but the standard is really without the `.html` extension, like so: `http://digitopia.github.io/research`. Much better right? :D

The only thing needed to change this is to edit the links in the `index.html` from something like this:

```html
<a href="http://digitopia.github.io/research.html">RESEARCH</a>
```

to this:

```html
<a href="http://digitopia.github.io/research">RESEARCH</a>
```

I would do it myself, but seems like good practice for @augusto666 💪.

**Comment by augusto666** [comment]
:) no worries!

**Comment by augusto666** [comment]
done
